### ISSUE TITLE
Needs rewrite and modularization

### ISSUE THREAD

**Issue by ifvictr** [ifvictr/wee#1]
Codebase should be split into smaller files instead of in the [app.js](https://github.com/ifvictr/oca/blob/master/app.js) file. Also will need to find a way to break out of callback hell. Just look at that code nested eight layers deep. For project structure, I have a few in mind (two to be specific), so either:
```
bin/
public/
routes/
views/
app.js
```
or:
```
config/
controllers/
helpers/
middlewares/
models/
public/
views/
app.js
```

**Comment by zanedb** [comment]
DO IT
